### ISSUE TITLE
Nemesis iptables rules issues

### ISSUE THREAD

**Issue by bogdando** [aphyr/jepsen#102]
First, on :start, it shall drop related, established as well as new connections. This would simulate traffic isolation better for systems with connections being tracked.

Second, it shall not cut off his ssh legs and allow traffic to the 22 port.

**Comment by bogdando** [comment]
@aphyr please take a look

**Comment by aphyr** [comment]
Jepsen's partitions are only between DB nodes. It should never snub the control node, so I don't see a need for a port 22 exception. (Also there are cases where I *want* to isolate port 22 between nodes)

**Comment by bogdando** [comment]
Thank you, it is clear now that I misunderstood the control node, I thought it should be one of the n{1..5}

**Comment by bogdando** [comment]
But what about the 2nd part? established and related shall be cut as well, aren't they? Otherwise network partition (isolation) is not complete

**Comment by bogdando** [comment]
Renamed, please consider to reopen

**Comment by bogdando** [comment]
I see, for the clean env you recommend in the setup guide, w/o accepting iptables rules, this works well. But if Jepsen framework is supposed to be used with arbitrary n1..n5 nodes, there may be ACCEPT rules for the cluster under test pre-created. Then, the rule will not match related traffic.

**Comment by aphyr** [comment]
It will match related traffic, because of the very next function, net/heal, which clears all iptables rules.
On Apr 20, 2016 2:42 AM, Bogdan Dobrelya <notifications@github.com> wrote:I see, for the clean env you recommend in the setup guide, w/o accepting iptables rules, this works well. But if Jepsen framework is supposed to be used with arbitrary n1..n5 nodes, there may be ACCEPT rules for the cluster under test pre-created. Then, the rule will not match related traffic.
